# This is the file that ties Swimm's pre-commit hooks to actions needed to run. 

- id: swimm-verify
  name: swimm-verify
  description: Verify all Swimm documentation to be current
  entry: hooks/swimm-verify.sh
  language: script

- id: swimm-export
  name: swimm-export
  description: Export swimm documentation against the current version
  entry: hooks/swimm-export.sh
  language: script
