# This is the file that ties Swimm's pre-commit hooks to actions needed to run. 

- id: swimm-verify
  name: swimm-verify
  description: Verify all Swimm documentation to be current.
  entry: hooks/swimm-verify.sh
  language: script

- id: swimm-verify-nonblocking
  name: swimm-verify-nonblocking
  description: Like swimm-verify, but don't block the commit on failure.
  entry: hooks/swimm-verify-nonblocking.sh
  language: script
